export enum ValidateProfileError {
  INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
  INCORRECT_AGE = 'INCORRECT_AGE',
  INCORRECT_COUNTRY = 'INCORRECT_COUNTRY',
  DATA_ERROR = 'DATA_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
}
